
### Include the objects in the MonteCarlo support directory
MonteCarloRHD += Particles_data.o Particles_init.o Particles_addNew.o Grid_getBlkIDFromPos.o
Simulation += reader.o random.o spherical.o rhd.o new_mcp.o relativity.o scattering.o opacity.o ionization.o transport.o emission.o
